Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest:80, host:8080
  config.vm.network "forwarded_port", guest:443, host:8443
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
