# создаются хосты master,node1 и node2
# провайдер - virtualbox
Vagrant.configure("2") do |config|      # настройки общие для всех VM
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.box = "ubuntu/focal64"      # образ системы используемый в VM
  config.vm.box_check_update = false    # проверка новых версий  образа

  (1..3).each do |i|  # настройка нескольких узлов в цикле от 1 до 2
    config.vm.define "vagrant#{i}" do |node| # определяем общие настройки для nodes
      node.vm.hostname = "vagrant#{i}" #hostname
      node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
      node.vm.network "forwarded_port", guest: 443, host: "844#{i}"
      node.vm.provider "virtualbox" do |vb| # "железо" для нодов
        vb.name = "vagrant#{i}"
        vb.memory = 1024
        vb.cpus = 1
        vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
      end
    end
  end
end
